USE [STG]

SELECT * FROM [DBO].[TB_STG_PEDIDO];

SELECT * FROM [DBO].[TB_STG_CLIENTE];

SELECT * FROM [DBO].[TB_STG_TIPO_CLIENTE];

SELECT * FROM [DBO].[TB_STG_CATEGORIA_PRODUTO];

SELECT * FROM [DBO].[TB_STG_PRODUTO];

SELECT * FROM [DBO].[TB_STG_ITEM_PEDIDO];