USE [STG]

SELECT * FROM [DBO].[TB_STG_PEDIDO];

SELECT * FROM [DBO].[TB_STG_CLIENTE];

SELECT * FROM [DBO].[TB_STG_TIPO_CLIENTE];

SELECT * FROM [DBO].[TB_STG_CATEGORIA_PRODUTO];

SELECT * FROM [DBO].[TB_STG_PRODUTO];

SELECT * FROM [DBO].[TB_STG_ITEM_PEDIDO];

SELECT
  COD_CLIENTE_OLTP
, NOM_CLIENTE
, EML_CLIENTE
, NOM_CIDADE_CLIENTE
, LOGRADOURO + ' -Num: '+ CONVERT(varchar(5), NUMERO) +' Complemento:'+ COMPLEMENTO
+' CEP: '+ CEP END_CLIENTE
FROM TB_STG_CLIENTE

USE STG;
SELECT * FROM [dbo].[TB_STG_TIPO_CLIENTE] ;
UPDATE [dbo].[TB_STG_TIPO_CLIENTE] 
SET DES_TIPO_CLIENTE = 'GOLDEN'
WHERE [COD_TIPO_CLIENTE_OLTP]=10

SELECT * FROM [dbo].[TB_STG_CATEGORIA_PRODUTO] ;
UPDATE [dbo].[TB_STG_CATEGORIA_PRODUTO] 
SET DES_CATEGORIA_PRODUTO = 'TENIS'
WHERE [COD_CATEGORIA_PRODUTO_OLTP]=140

SELECT 
YEAR(P.DATA_PEDIDO) * 100 + MONTH(P.DATA_PEDIDO) AS NUM_MES_PEDIDO,
CLI.COD_ESTADO_OLTP,
CLI.COD_CLIENTE_OLTP,
CLI.COD_TIPO_CLIENTE_OLTP,
I.COD_PRODUTO_OLTP,
SUM(I.VLR_UNITARIO_ITEM * I.QTD_ITEM) VLR_PEDIDO,
SUM (I.QTD_ITEM) QTD_ITEM_PEDIDO,
(YEAR (GETDATE())*100 + MONTH(GETDATE())) *100 +  DAY(GETDATE()) AS DATA_CARGA
FROM   TB_STG_ITEM_PEDIDO AS I  
               INNER JOIN  TB_STG_PEDIDO   AS  P   ON 
(P.COD_PEDIDO_OLTP=I.COD_PEDIDO_OLTP)
               INNER JOIN TB_STG_CLIENTE AS CLI ON 
(P.COD_CLIENTE_OLTP=CLI.COD_CLIENTE_OLTP)
GROUP BY
YEAR(P.DATA_PEDIDO) * 100 + MONTH(P.DATA_PEDIDO) ,
CLI.COD_ESTADO_OLTP,
CLI.COD_CLIENTE_OLTP,
CLI.COD_TIPO_CLIENTE_OLTP,
I.COD_PRODUTO_OLTP

ALTER TABLE DBO.TB_FATO_PEDIDO ALTER COLUMN DATA_CARGA INT
;
ALTER TABLE DBO.TB_FATO_PEDIDO ALTER COLUMN QTD_ITEM_PEDIDO DECIMAL(38,0)
;
ALTER TABLE DBO.TB_FATO_PEDIDO ALTER COLUMN VLR_PEDIDO DECIMAL(38,5)
;
ALTER TABLE DBO.TB_FATO_PEDIDO ALTER COLUMN NUM_MES_PEDIDO INT