Create database STG;

USE STG;

CREATE TABLE TB_STG_ITEM_PEDIDO (
                COD_PEDIDO_OLTP INTEGER,
                COD_PRODUTO_OLTP  INTEGER,
                VLR_UNITARIO_ITEM NUMERIC(22,5),
                QTD_ITEM NUMERIC(10)
);


CREATE TABLE TB_STG_PRODUTO (
                COD_CATEGORIA_PRODUTO_OLTP INTEGER,
                COD_PRODUTO_OLTP INTEGER,
                NOM_PRODUTO VARCHAR(40)
);


CREATE TABLE TB_STG_CATEGORIA_PRODUTO (
                COD_CATEGORIA_PRODUTO_OLTP INTEGER,
                DES_CATEGORIA_PRODUTO VARCHAR(40)
);


CREATE TABLE TB_STG_PEDIDO (
                COD_PEDIDO_OLTP INTEGER NOT NULL,
                DATA_PEDIDO DATE,
                COD_CLIENTE_OLTP  INTEGER NOT NULL,
               
);


CREATE TABLE TB_STG_TIPO_CLIENTE (
                COD_TIPO_CLIENTE_OLTP INTEGER NOT NULL,
                DES_TIPO_CLIENTE VARCHAR(40) NOT NULL
);


CREATE TABLE TB_STG_CLIENTE (
                COD_TIPO_CLIENTE_OLTP INTEGER NOT NULL,
                NOM_CLIENTE  VARCHAR(40) NOT NULL,
                EML_CLIENTE VARCHAR(40) NOT NULL,
                NOM_CIDADE_CLIENTE VARCHAR(50) NOT NULL,
                COD_CLIENTE_OLTP INTEGER,
                COD_ESTADO_OLTP VARCHAR(2),
                LOGRADOURO VARCHAR(30),
                NUMERO INTEGER ,
                COMPLEMENTO VARCHAR(20) ,
                CEP VARCHAR(10) 
);