
Create database DW;

USE DW;

	   
/***************SCD2***************************/
CREATE TABLE TB_DIM_TIPO_CLIENTE (
       SRK_TIPO_CLIENTE     INTEGER  NOT NULL,
       COD_TIPO_CLIENTE_NK INTEGER NOT NULL,
       DES_TIPO_CLIENTE     VARCHAR(40) NOT NULL,
       CONSTRAINT XPKTB_DIM_TIPO_CLIENTE 
              PRIMARY KEY (SRK_TIPO_CLIENTE)
);

/***************CHAVE AUTO INCREMENTO - SCD1***************************/
CREATE TABLE TB_DIM_CLIENTE (
       SRK_CLIENTE          INTEGER IDENTITY(1,1) NOT NULL,
       COD_CLIENTE_NK     INTEGER NOT NULL,
       NOM_CLIENTE          VARCHAR(40) NOT NULL,
	   END_CLIENTE          VARCHAR(100) NOT NULL,
       EML_CLIENTE          VARCHAR(50) NOT NULL,
       NOM_CIDADE_CLIENTE   VARCHAR(40) NOT NULL,
       CONSTRAINT XPKTB_DIM_CLIENTE 
              PRIMARY KEY (SRK_CLIENTE)
);

/****CARGA FRIA *****/
CREATE TABLE TB_DIM_MES (
       NUM_MES_ANO          NUMERIC(10) NOT NULL,
       NOM_MES              VARCHAR(50) NOT NULL,
       NUM_MES              INTEGER NOT NULL,
       NOM_MES_ANO          VARCHAR(100) NOT NULL,
       NOM_BIMESTRE_ANO     VARCHAR(100) NOT NULL,
       NOM_TRIMESTRE_ANO    VARCHAR(100) NOT NULL,
       NOM_SEMESTRE_ANO     VARCHAR(50) NOT NULL,
       NOM_BIMESTRE         VARCHAR(50) NOT NULL,
       NOM_TRIMESTRE        VARCHAR(50) NOT NULL,
       NOM_SEMESTRE         VARCHAR(50) NOT NULL,
       CONSTRAINT XPKTB_DIM_MES 
              PRIMARY KEY (NUM_MES_ANO)
);

/***************CHAVE AUTO INCREMENTO - SCD1***************************/
CREATE TABLE TB_DIM_ESTADO (
       SRK_ESTADO          INTEGER IDENTITY(1,1) NOT NULL,
       COD_ESTADO_NK      VARCHAR(2) NOT NULL, ---CODIGO OLTP VAI SER UMA SIGLA VINDA DO EXCEL.
       NOM_ESTADO           VARCHAR(20) NOT NULL,
       CONSTRAINT XPKTB_DIM_ESTADO1 
              PRIMARY KEY (SRK_ESTADO)
);

/*************** SCD2***************************/
CREATE TABLE TB_DIM_CATEGORIA_PRODUTO (
       SRK_CATEGORIA_PRODUTO INTEGER NOT NULL,
       COD_CATEGORIA_PRODUTO_NK INTEGER NOT NULL,
       DES_CATEGORIA_PRODUTO VARCHAR(40) NOT NULL, -----MUDA A DESCRIÇÃO GERA OUTRA VERSAO***********************/
       CONSTRAINT PK_TB_DIM_CATEGORIA_PRODUTO 
              PRIMARY KEY (SRK_CATEGORIA_PRODUTO)
	 
);

/***************CHAVE AUTO INCREMENTO -SCD1***************************/
CREATE TABLE TB_DIM_PRODUTO (
       SRK_PRODUTO          INTEGER IDENTITY(1,1) NOT NULL,
       NOM_PRODUTO          VARCHAR(40) NOT NULL,
       COD_PRODUTO_NK     INTEGER NOT NULL,
	   SRK_CATEGORIA_PRODUTO INTEGER NOT NULL,
       CONSTRAINT XPKTB_DIM_PRODUTO 
              PRIMARY KEY (SRK_PRODUTO),
	   CONSTRAINT FK_CATEGORIA_DIM_PRODUTO
       FOREIGN KEY (SRK_CATEGORIA_PRODUTO)
                             REFERENCES TB_DIM_CATEGORIA_PRODUTO  (SRK_CATEGORIA_PRODUTO));



CREATE TABLE TB_FATO_PEDIDO (
       NUM_MES_PEDIDO       NUMeric(10) NOT NULL,
       SRK_ESTADO           INTEGER NOT NULL,
       SRK_CLIENTE          INTEGER NOT NULL,
       SRK_TIPO_CLIENTE     INTEGER NOT NULL,
       SRK_PRODUTO          INTEGER NOT NULL,
       VLR_PEDIDO           NUMeric(22,10) NOT NULL,
       QTD_ITEM_PEDIDO      NUMeric(10) NOT NULL,
      DATA_CARGA NUMeric(10) NOT NULL,
     
       CONSTRAINT XPKTB_FATO_PEDIDO 
              PRIMARY KEY (NUM_MES_PEDIDO, SRK_ESTADO, SRK_CLIENTE, 
              SRK_TIPO_CLIENTE, SRK_PRODUTO), 
       CONSTRAINT FK_PRODUTO_FTO_PEDIDO
              FOREIGN KEY (SRK_PRODUTO)
                             REFERENCES TB_DIM_PRODUTO  (SRK_PRODUTO), 
       CONSTRAINT FK_MES_FTO_PEDIDO
              FOREIGN KEY (NUM_MES_PEDIDO)
                             REFERENCES TB_DIM_MES  (NUM_MES_ANO), 
             CONSTRAINT FK_TIPO_CLIENTE_FTO_PEDIDO
              FOREIGN KEY (SRK_TIPO_CLIENTE)
                             REFERENCES TB_DIM_TIPO_CLIENTE  (
              SRK_TIPO_CLIENTE), 
       CONSTRAINT FK_CLIENTE_FTO_PEDIDO
              FOREIGN KEY (SRK_CLIENTE)
                             REFERENCES TB_DIM_CLIENTE  (SRK_CLIENTE), 
       CONSTRAINT FK_ESTADO_FTO_PEDIDO
              FOREIGN KEY (SRK_ESTADO)
                             REFERENCES TB_DIM_ESTADO  (SRK_ESTADO)
);




