use [dw]

select * from [dbo].[TB_DIM_MES]

select * from [dbo].[TB_DIM_ESTADO]

select * from [dbo].[TB_DIM_CLIENTE]

USE DW;
------Script auxliar TB_DIM_TIPO_CLIENTE
ALTER TABLE DBO.TB_DIM_TIPO_CLIENTE ADD VERSAO INT
;
ALTER TABLE DBO.TB_DIM_TIPO_CLIENTE ADD DATA_INICIO_VIGENCIA DATETIME
;
ALTER TABLE DBO.TB_DIM_TIPO_CLIENTE ADD DATA_FIM_VIGENCIA DATETIME
;
SELECT * FROM [dbo].[TB_DIM_TIPO_CLIENTE]
ORDER BY 2

INSERT INTO [dbo].[TB_DIM_TIPO_CLIENTE] VALUES (0,0,'SCD2',NULL, NULL, NULL);

ALTER TABLE DBO.TB_DIM_CATEGORIA_PRODUTO ADD VERSAO INT
;
ALTER TABLE DBO.TB_DIM_CATEGORIA_PRODUTO ADD DATA_INICIO_VIGENCIA DATETIME
;
ALTER TABLE DBO.TB_DIM_CATEGORIA_PRODUTO ADD DATA_FIM_VIGENCIA DATETIME

INSERT INTO [dbo].[TB_DIM_CATEGORIA_PRODUTO] VALUES (0,0,'SCD2',NULL, NULL, NULL);

select * from dbo.TB_DIM_CATEGORIA_PRODUTO

select * from dbo.TB_DIM_PRODUTO where COD_PRODUTO_NK = 11

use STG
select * from dbo.TB_STG_PRODUTO where COD_PRODUTO_OLTP = 11

use dw
select * from dbo.TB_DIM_CATEGORIA_PRODUTO where COD_CATEGORIA_PRODUTO_NK = 80
