use [dw]

select * from [dbo].[TB_DIM_MES]

select * from [dbo].[TB_DIM_ESTADO]

select * from [dbo].[TB_DIM_CLIENTE]

USE DW;
------Script auxliar TB_DIM_TIPO_CLIENTE
ALTER TABLE DBO.TB_DIM_TIPO_CLIENTE ADD VERSAO INT
;
ALTER TABLE DBO.TB_DIM_TIPO_CLIENTE ADD DATA_INICIO_VIGENCIA DATETIME
;
ALTER TABLE DBO.TB_DIM_TIPO_CLIENTE ADD DATA_FIM_VIGENCIA DATETIME
;
SELECT * FROM [dbo].[TB_DIM_TIPO_CLIENTE]
ORDER BY 2

INSERT INTO [dbo].[TB_DIM_TIPO_CLIENTE] VALUES (0,0,'SCD2',NULL, NULL, NULL);

ALTER TABLE DBO.TB_DIM_CATEGORIA_PRODUTO ADD VERSAO INT
;
ALTER TABLE DBO.TB_DIM_CATEGORIA_PRODUTO ADD DATA_INICIO_VIGENCIA DATETIME
;
ALTER TABLE DBO.TB_DIM_CATEGORIA_PRODUTO ADD DATA_FIM_VIGENCIA DATETIME

INSERT INTO [dbo].[TB_DIM_CATEGORIA_PRODUTO] VALUES (0,0,'SCD2',NULL, NULL, NULL);

select * from dbo.TB_DIM_CATEGORIA_PRODUTO

select * from dbo.TB_DIM_PRODUTO where COD_PRODUTO_NK = 11

use STG
select * from dbo.TB_STG_PRODUTO where COD_PRODUTO_OLTP = 11

use dw
select * from dbo.TB_DIM_CATEGORIA_PRODUTO where COD_CATEGORIA_PRODUTO_NK = 80


USE DW;

insert into tb_dim_categoria_produto  values (-1, -1, 'NÃO CADASTRADO',NULL,NULL,NULL);

SET IDENTITY_INSERT tb_dim_produto ON; 

insert into tb_dim_produto ([SRK_PRODUTO],[NOM_PRODUTO],[COD_PRODUTO_NK],[SRK_CATEGORIA_PRODUTO]) values (-1,'NÃO CADASTRADO',-1, -1);
SET IDENTITY_INSERT tb_dim_produto OFF; 

SET IDENTITY_INSERT dbo.tb_dim_cliente ON;  
insert into tb_dim_cliente (SRK_CLIENTE, [COD_CLIENTE_NK],[NOM_CLIENTE],
[END_CLIENTE],[EML_CLIENTE],[NOM_CIDADE_CLIENTE])values(-1,-1,'NÃO CADASTRADO','NÃO CADASTRADO','NÃO CADASTRADO','NÃO CADASTRADO');
SET IDENTITY_INSERT dbo.tb_dim_cliente OFF; 

SET IDENTITY_INSERT tb_dim_estado ON; 
insert into tb_dim_estado ([SRK_ESTADO],[COD_ESTADO_NK],[NOM_ESTADO]) values (-1, '-1', 'NÃO CADASTRADO');
SET IDENTITY_INSERT tb_dim_estado OFF; 

insert into tb_dim_tipo_cliente values (-1, -1, 'NÃO CADASTRADO',NULL,NULL,NULL);

select * from dbo.tb_fato_pedido


